---
name: Lint

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]
permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          activate-environment: true

      - name: Install dependencies
        run: uv sync --frozen --group lint

      - name: Python linting
        run: ruff check .

      - name: Python format checking
        run: ruff format --check .

      - name: Python type checking
        run: mypy .
